### ISSUE TITLE
Don't apply scrambling frame-by-frame

### ISSUE THREAD

**Issue by tonyrobustelli95** [bissim/mpeg-scrambling#3]
Our idea is to apply the scrambling only on type I frames and not frame-by-frame as the current implementation.

**Comment by bissim** [comment]
[`mpeg.c`](https://github.com/bissim/mpeg-scrambling/blob/915545e75f88e6cb7b2de267026fcc680a319ac8/mpeg-scrambling2.0/mpeg.c#L1103), line _1103_: we should consider adding frame check here.

**Comment by bissim** [comment]
Currently, we still apply scrambling frame by frame, however **we kept face detection limited to intraframes**, according to e13141d and cf59d8a.
